### ISSUE TITLE
pip install dolphindb ERROR

### ISSUE THREAD

**Issue by liuzhidong** [dolphindb/api_python3#10]
macOS High Sierra 10.13.6 (17G14042)
conda 22.9.0
python 3.7.13
RUN:
pip install dolphindb
OUTPUT:
ERROR: Could not find a version that satisfies the requirement dolphindb (from versions: none)
ERROR: No matching distribution found for dolphindb

**Comment by hzwale** [comment]
问题收到，DolphinDB将在python api的readme中针对有时会安装失败的问题进行详细说明，敬请期待。

**Comment by liuzhidong** [comment]
谢谢

**Comment by hzwale** [comment]
已在https://github.com/dolphindb/api_python3/blob/master/README_CN.md引言部分补充说明，请参阅。
