### ISSUE TITLE
对python3.11的支持

### ISSUE THREAD

**Issue by chen-001** [dolphindb/api_python3#11]
您好开发者，非常感谢您，请问将来会支持python3.11吗？大概什么时间会上线呢？

**Comment by hzwale** [comment]
会支持，预计5月初会上线。

**Comment by chen-001** [comment]
感谢！！非常期待了😉

**Comment by hzwale** [comment]
sorry，进度有点延迟，预计要到6月了。

**Comment by chen-001** [comment]
没关系，不着急，非常感谢您和您的团队！

**Comment by loyaliu** [comment]
现在8月了，催更啊

**Comment by dingo9** [comment]
催更+1

**Comment by halfelf** [comment]
一年都要过完了

**Comment by hzwale** [comment]
不好意思，研发部门有点忙，预计要延期到明年一季度了

**Comment by peeyee** [comment]
已于[1.30.22.6](https://github.com/dolphindb/api_python3/blob/master/ReleaseNotes/1.30.22.6.md)支持。
