### ISSUE TITLE
mac系统无法安装dolphindb的python接口包

### ISSUE THREAD

**Issue by hjames17** [dolphindb/api_python3#3]
这个问题有解决办法吗？还是我装错了？
none of the wheel's tags ... are compatible 
ERROR: Could not find a version that satisfies the requirement dolphindb==1.30.0.5 (from versions: none)
ERROR: No matching distribution found for dolphindb==1.30.0.5

**Comment by qiuwei** [comment]
目前还不支持mac os

**Comment by glacierck** [comment]
一年过去了还不支持在venv里装吗？能说说问题在哪不？有那么特殊的？

**Comment by hzwale** [comment]
支持mac的python api版本正在测试，预计本月底发布，敬请期待！

**Comment by hzwale** [comment]
已发布的1.30.19.1版本已支持mac，请试用！
