### ISSUE TITLE
无法安装 pip install dolphindb

### ISSUE THREAD

**Issue by chenjie0927** [dolphindb/api_python3#5]
ERROR: Could not find a version that satisfies the requirement dolphindb (from versions: none)
ERROR: No matching distribution found for dolphindb

**Comment by windancer79** [comment]
pip 方式安装 linux下支持 python 3.6，3.7， 3.8； windows下目前支持 python 3.6, 3.7

**Comment by chenjie0927** [comment]
windows下目前支持 python 3.6, 3.7啊？我用的3.8版本

**Comment by HiramYong** [comment]
支持树莓派的armv732版吗？在树莓派里使用docker ubuntu镜像

**Comment by FangyangJz** [comment]
Readme 上写win 支持到 3.9，看了下pypi没有发布版本，pip 安装不上

**Comment by hzwale** [comment]
目前支持的操作系统和Python 版本号如下：
Windows(amd64)  Python 3.6-3.9
Linux(x86_64)        Python 3.6-3.9
Linux(aarch64)      Conda 环境下的 Python 3.7-3.9
Mac(x86_64)         Conda 环境下的 Python 3.6-3.9
Mac(arm64)          Conda 环境下的 Python 3.8-3.9
