### ISSUE TITLE
Does DolphinDB support User Defined Function?

### ISSUE THREAD

**Issue by AbdelouahabKhelifati** [dolphindb/api_python3#6]
I am currently working on a benchmark of time series database systems for analytical (complex) queries. These queries are algorithms that cannot (easily) be implemented in SQL language so they require a third-party programming language such as C, C++, Python, Java, etc.

I am writing to you to ask if DolphinDB support such a feature of a third-party programming language for User Defined Functions?

**Comment by ShenaMao** [comment]
> I am currently working on a benchmark of time series database systems for analytical (complex) queries. These queries are algorithms that cannot (easily) be implemented in SQL language so they require a third-party programming language such as C, C++, Python, Java, etc.
> 
> I am writing to you to ask if DolphinDB support such a feature of a third-party programming language for User Defined Functions?

Hi, actually DolphinDB script language drew inspiration from popular programming languages such as SQL and Python. It provides a highly expressive programming language that offers high performance and enables rapid development.

Therefore, you could use DolphinDB script language that not only in SQL but also in python-like structure. We support User Defined Functions, vector programming, SQL programming, imperative programming, higher order function, etc.

For further understanding of our DolphinDB script language, please refer to https://github.com/dolphindb/Tutorials_EN/blob/master/DolphinDB_Programming_Guide.md

And we also offer multiple types of plugins, such as python plugins, which allows users to call python packages in script. DolphinDB database supports dynamic loading of external plugins to extend system functionality. The plug-in can be written in C++, you could refer to https://github.com/dolphindb/DolphinDBPlugin
