### ISSUE TITLE
通过pip 安装 报DLL的问题.python版本3.88

### ISSUE THREAD

**Issue by cjj208** [dolphindb/api_python3#9]
ImportError: DLL load failed while importing dolphindbcpp: 动态链接库(DLL)初始化例程失败。

**Comment by Wilson1823** [comment]
@cjj208 
You might be facing this issue because of the following reasons

- You are running 32-bit Python or 32-bit OS
- You have not installed the [Microsoft Visual C++ Redistributable](https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads) package
- Your CPU does not support AVX instructions.

**Comment by lppgo** [comment]
我也遇到这个问题。我在win10 python3.8 遇到相同的问题，反复测试好几次。最后切换安装python3.7.9 并对应使用dolphindb 3.17.4  发现可以运行

**Comment by lppgo** [comment]
> ImportError: DLL load failed while importing dolphindbcpp: 动态链接库(DLL)初始化例程失败。

我也遇到这个问题。我在win10 python3.8 遇到相同的问题，反复测试好几次。最后切换安装python3.7.9 并对应使用dolphindb 3.17.4 发现可以运行

**Comment by QGB** [comment]
```
C:\QGB\Anaconda3\lib\site-packages\dolphindb\__init__.py in <module>
      1 name = "dolphindb"
----> 2 from .session import session
      3 from .session import DBConnectionPool
      4 from .session import BlockReader
      5 from .session import PartitionedTableAppender

C:\QGB\Anaconda3\lib\site-packages\dolphindb\session.py in <module>
     23
     24 sys.path.append(os.path.dirname(__file__))
---> 25 import dolphindbcpp  as ddbcpp
     26
     27

ImportError: DLL load failed: 动态链接库(DLL)初始化例程失败。

```

**Comment by hzwale** [comment]
请问你的python是什么版本？

目前windows 版本的 DolphinDB Python API 支持 Python 3.6-3.8 版本，但仅支持 conda 环境下的 python 3.8；
请在conda环境下配置python3.8 > 3.8.0（ps：windows下，python 3.8.0 暂不支持 DolphinDB Python API），pip安装 Python API 后 import 。

**Comment by mgttt** [comment]
3.9 win 非conda 何时发布？

**Comment by hzwale** [comment]
版本在测试中，预计下周初发布。
